- name: Create service directories
      ansible.builtin.file:
        path: "{{ base_path }}/{{ item }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      loop: "{{ homelab_services }}"

    - name: Copy docker-compose files
      ansible.builtin.copy:
        src: "../services/{{ item }}/docker-compose.yml"
        dest: "{{ base_path }}/{{ item }}/docker-compose.yml"
        mode: '0644'
      loop: "{{ homelab_services }}"
